### ISSUE TITLE
Make linting optional

### ISSUE THREAD

**Issue by miljan-aleksic** [yamafaktory/shrimpit#2]
Hi, I like the tool, thank you for it.

I am trying to use it, but getting linting error messages. I have my own standards and tools for that, so would like to only use it to find out unused exports. Could you add an option to ignore linting or even better, make the linting optional?

**Comment by yamafaktory** [comment]
Hi @miljan-aleksic,

Thank you for the feedback! In fact, this project uses the [babylon](https://github.com/babel/babylon) JavaScript parser underneath (the one used by Babel). As a consequence, I guess what you get are syntax errors raised by the parser and there's currently no available option in order to bypass this behavior.

Can you please provide a small example of what is breaking the parsing process (maybe a gist) so that I can be sure about the current issue?

**Comment by miljan-aleksic** [comment]
The errors were triggered because I was trying to check the entire project folder, including the dist where JS was already compiled. After improving my project folder structure I was able to rerun only on the src folder and found out some confusing results.

```shell
shrimpit --tree src

> Files tree  

{ src: 
   { layouts: 
      { 'Default.js': 
         { exports: [ 'name', 'functional', 'render' ],
           imports: [ 'each', 'merge', 'filter' ] },
        'index.js': { exports: [], imports: [ 'Default' ] } }
...}

> Unused exports  

[ 'name',
  'functional',
  'render'
  ...]
```

This is the Default.js source code:

```js
export default {
  name: '...',
  functional: true,
  render () {...}
...}

In that file I'm exporting the entire Object meant to be used as a whole, and as such its properties are never imported. In fact, I'm not sure if I could even do that using ES6.

**Comment by yamafaktory** [comment]
Hi @miljan-aleksic,

Thank you for the small example 👍 . What you are doing is totally fine as you are using a default _unnamed_ export (https://developer.mozilla.org/en/docs/web/javascript/reference/statements/export) and therefore this is a real bug. I'm going to investigate and find a way for fixing that.

**Comment by yamafaktory** [comment]
Hi @miljan-aleksic,

I've just published a new version with a fix, please give it a try, thanks!

**Comment by miljan-aleksic** [comment]
Hi!

Seems not solved, but the result did changed. Now it outputs:

```js
shrimpit src --tree

> Files tree

{ src: 
   { layouts: 
      { 'Default.js': 
         { exports: [ 'src/layouts/Default', 'render', 'e' ],
           imports: [ 'each', 'merge', 'filter' ] },
        'index.js': { exports: [], imports: [ 'src/layouts/Default' ] } }
...}

> Unused exports  

[ 'render',
  'e'
...]
```

The `default.js` module doesn't even have an `e` property.

**Comment by yamafaktory** [comment]
@miljan-aleksic can you provide the complete content of the `Default.js` file?

**Comment by miljan-aleksic** [comment]
Yes, it's an open source project, so you can test it directly, just use the `next` branch - https://github.com/vuikit/vuikit/blob/next/src/layouts/Default.js

**Comment by yamafaktory** [comment]
@miljan-aleksic Thanks a lot! Will try to check that A.S.A.P. 👍

**Comment by yamafaktory** [comment]
@miljan-aleksic please try the latest version, should be fixed hopefully 🤞.

**Comment by miljan-aleksic** [comment]
Thanks @yamafaktory. We are getting closer :D

It outputs 

```js
> Unused exports  

[ 'src/lib/Datepicker/Header',
  'src/lib/Table/columns/core',
  'src/lib/Table/index',
  'src/lib/Tabs/core',
  'src/pages/_mixin' ] 
````

The `src/lib/Datepicker/Header` is imported in a script insdie .vue file. Being those special, we can accept the result as correct. The `src/lib/Table/columns/core`, though, is imported from the [sibling file](https://github.com/vuikit/vuikit/blob/next/src/lib/Table/columns/Default.js#L1), so that result seems wrong. Similar happens with the rest.

**Comment by yamafaktory** [comment]
@miljan-aleksic Thanks for your feedback. Indeed, `.vue` files can't be parsed by Babylon. Regarding the second point, I'll try to fix it 👍 .

**Comment by yamafaktory** [comment]
@miljan-aleksic I pushed a new version again, with Vue templates support. Hope everything is fine now, please feel free to open a new issue if this is not the case, thanks!

**Comment by miljan-aleksic** [comment]
Awesome @yamafaktory! Now seems working fine :) Thank you for the extra mile!!
