### ISSUE TITLE
Error on React fragments short syntax

### ISSUE THREAD

**Issue by underblob** [yamafaktory/shrimpit#75]
Hi, I'm seeing the tool exits with an error when it gets to a React fragment written in short syntax (`<> ... </>`):
```
! SyntaxError: Unexpected token (17:3) in src/components/[ ... ].js
```
https://reactjs.org/docs/fragments.html#short-syntax

**Comment by Eugen-Ask** [comment]
The same problem. Is anybody going to fix it?

**Comment by yamafaktory** [comment]
Hi, I'll have a look at it. I'm pretty sure this can be easily fixed by updating the dependencies 🤞.

**Comment by yamafaktory** [comment]
Alright, we need to use the new @babel/parser & @babel/traverse modules since everything has been reworked in the Babel ecosystem. Hopefully, I've it already working in a branch, just need a small additional tweak for the decorators plugin (not sure to keep it...). It should then parse React Fragments right without any issue 🚀.

**Comment by yamafaktory** [comment]
@Eugen-Ask & @underblob sorry for the late support... The issue has been addressed in https://github.com/yamafaktory/shrimpit/releases/tag/v0.21.0. Please give it a try so that I can close that issue 👍.

**Comment by Eugen-Ask** [comment]
@yamafaktory thanks

**Comment by underblob** [comment]
Hi @yamafaktory sorry for the delay getting back to you. I did a quick run with...
```
npx shrimpit ./src
```
...still seeing the syntax error on fragment tags. Was the NPM registry updated to the latest?

**Comment by underblob** [comment]
OK seems like that's the problem. The NPM registry has version 0.20: https://www.npmjs.com/package/shrimpit

**Comment by underblob** [comment]
```
npx https://github.com/yamafaktory/shrimpit\#v0.21.0 ./src
```
LGTM, thanks @yamafaktory!

**Comment by yamafaktory** [comment]
Oh my bad... @underblob https://github.com/yamafaktory/shrimpit/tree/v0.21.1 has been released & published to NPM this time 😅.
